---
title: "initial_model4_and pre"
output: pdf_document
date: "2023-07-29"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(spdep)
library(glmnet)
library(RColorBrewer)
library('spBayes')
library(ggplot2)
library(optimx)
```


# Null dataset generation
```{r}

Null_dataset_gen<-function(){
df <- list()
df$meta <- list()
df$meta$cell <- c(1:500)
df$meta$x <- runif(500, min = 0, max = 100)
df$meta$y <- runif(500, min = 0, max = 100)

df$meta$gene<- matrix(c(runif(2000, min = 0, max = 1)),ncol = 4)

df$meta$locat <- data.frame(df$meta$x,df$meta$y)
df$para$dist <- as.matrix(dist(df$meta$locat))
df$meta$cell_type<- sample(1:4, length(df$meta$cell), replace = TRUE)
return(df)
}
df = Null_dataset_gen()
```
## plot different cell
```{r}
plot(df$meta$locat, pch=19,cex = 0.5, col = as.numeric(df$meta$cell_type))
plot(df$meta$locat, pch=19,cex = 0.5, col = ifelse(df$meta$cell_type %in% c(3,4), "grey", df$meta$cell_type))
table(df$meta$cell_type)

```
# Finding Neighbour
## Weight KNN
```{r}
## Weighted K-NN for lr pairs

get_lr_wknn <- function(obj,sender,receiver, k){
  
  if(!all(c(sender, receiver) %in% unique(obj$meta$cell_type))) {
    stop("Can not find sender/receiver in the data")}
  
  else {
    
    #distance matrix
    
    distance <- obj$para$dist[obj$meta$cell_type == receiver, obj$meta$cell_type == sender]
    
    R <- list()
    
    #the indix of receiver
    R$indices <- as.matrix(t(head(apply(distance, 1, function(x) as.numeric(colnames(distance)[order(x,decreasing = FALSE)])),k)))
    
    
   #the distances of receiver from sender
    R$distances <- t(head(apply(distance, 1, function(x) sort(x, decreasing = FALSE)), k))
    
    weighted_counts <- R$distances
    percentile_weight <- head(sort(weighted_counts), length(weighted_counts) * 0.35)
    
    index_wknn <- t(apply(weighted_counts, 1 , function(x) x %in% percentile_weight))
    
     lr_wknn  <- R$indices * index_wknn
     
     lr_wknn[lr_wknn == 0 ] <- NA
     
     lr_wknn <- cbind(lr_wknn,obj$meta$x[obj$meta$cell_type == receiver])
     lr_wknn <- cbind(lr_wknn,obj$meta$y[obj$meta$cell_type == receiver])
     
     
     name <- c(c(1:k),"X","Y")
     
     
     colnames(lr_wknn) <-  name
    
    return(lr_wknn)
  }
}
  
  
## lr_example <- get_lr_wknn(df,
#            sender = 1,
#            receiver = 2,
#            k = 4)


```

## create lr index 
```{r}
 create_lr_index <- function(lrpair, Nopairadd = TRUE ){
   if(Nopairadd) {
    lrpair[,1]<- ifelse(is.na(lrpair[,1]), "0",lrpair[,1] )
   }
   
    A = rep(row.names(lrpair), each = ncol(lrpair)-2 )
    B = as.vector(t(lrpair[,-c(ncol(lrpair)-1, ncol(lrpair))]))
    
    lr_index <- cbind(A,B)
    
    lr_index <- lr_index[complete.cases(lr_index),]
    
    return(lr_index)
  }


lr_index_example <- create_lr_index(lr_example)
lr_index_example



```



##  plot lr pairs 


```{r}

find_row_list_number <- function(lr_index,list_of_lists) {
         
       for (i in 1: length(list_of_lists)) {
          if (all(lr_index %in% list_of_lists[[i]])) {
                       ind = i 
                        break
          }
       }
  return(ind)
}

plot_lr_pair <- function(obj, lr_pair, arrows = T, cluster = list()){
  #obj = df
   cell_index <- unique(as.numeric(c(rownames(lr_pair),as.numeric(lr_pair))))
  
    lr_index <- create_lr_index(lr_pair,Nopairadd = FALSE)
    
    lr_uni <- as.vector(unique(lr_index))
    
    lr_meta <- obj$meta$locat[lr_uni,]
    recepter <- obj$meta$cell_type[as.numeric(rownames(lr_pair)[1])]
    ligand <- obj$meta$cell_type[as.numeric(lr_pair)[1]]
    
    celltype <- as.vector(obj$meta$cell_type)
    ct_index <- as.vector(unique(celltype))
    color <- match(celltype,ct_index)
    
    

     plot(locat, pch = 19, cex = 0.5, col = ifelse(celltype %in% c(recepter, ligand), color, "grey"))

     text(lr_meta[lr_index,], lr_uni, pos = 3)
  

for (i in 1:nrow(lr_index)) {
      #sender
       A = lr_index[i,2]
      #receiver
      B = lr_index[i,1]
      
      x1 <- lr_meta[rownames(lr_meta) == A, 1]
      y1 <- lr_meta[rownames(lr_meta) == A, 2]
      x2 <- lr_meta[rownames(lr_meta) == B, 1]
      y2 <- lr_meta[rownames(lr_meta) == B, 2]
      
      
if (length(cluster) == 0 ){
if (arrows)  {
   arrows(x1, y1, x2, y2, length = 0.1)
}
else{
    lines(c(x1, x2), c(y1, y2), col = 1 )
}
      
}
  else{
    
    if (arrows)  {
   arrows(x1, y1, x2, y2, length = 0.1, col =as.numeric(find_row_list_number(lr_index[i, ], cluster)))
     }
else{
      lines(c(x1, x2), c(y1, y2), col = as.numeric(find_row_list_number(lr_index[i, ],cluster)))
     }
  }
  
}
}


#example  



    
    
```
## find neighbourhoods
```{r}

find_network <- function(obj, lr_pairs, plot = TRUE) {
  
  find_neighbor <- function(lr_pairs, Nopairadd = TRUE){
    
  lr_index <- create_lr_index(lr_pairs)
  neighbor <- list()
  
  for (value in unique(lr_index[, 1])) {
    # Extract rows with the current value
    rows <- lr_index[lr_index[,1] == value, ]
    # Append the rows to the result list as a matrix
    neighbor[[length(neighbor) + 1]] <- matrix(rows, ncol = 2, byrow = FALSE)
  }
  
  # Return the result
  return(neighbor)
}
  
  if(plot){
    neighbor_plot <- find_neighbor(lr_pairs,Nopairadd = FALSE)
    plot_lr_pair(obj, lr_pairs, arrows = T, cluster = neighbor_plot)
    
  }
  
  

  network <- find_neighbor(lr_pairs)
  return(network)
  
}

find_network(df,lr_example)


```
# SVC model
##dataset generating

```{r}
 build_dataset <- function(df, lr,recepter,ligand ) {
    
    lr_network <- find_network(df, lr,plot = FALSE)
    
      
      recepter_list <- df$meta$gene[,colnames(df$meta$gene) == recepter]
      ligand_list <- df$meta$gene[,colnames(df$meta$gene) == ligand]
      
  #   print(head(recepter_list,20))
  #   print(head(ligand_list,20))
      
      
        dataset <- vector("list", length(lr_network))  
  
    for (j in 1:length(lr_network)) {
      single_network <- lr_network[[j]]
      
      for (i in 1:(length(single_network)/2)) {
        
        if (length(single_network) == 2) {
          receptor_expression <- ifelse(is.na(recepter_list[as.numeric(single_network[1])]), 0, recepter_list[as.numeric(single_network[1])])
          ligand_expression <- ifelse(is.na(ligand_list[as.numeric(single_network[2])]) || single_network[2] == 0 ,0,ligand_list[as.numeric(single_network[2])])
          
        } else {
          row <- single_network[i, ]
          receptor_expression <- ifelse(is.na(recepter_list[as.numeric(row[1])]), 0 , recepter_list[as.numeric(row[1])] )
          
          ligand_expression <- ifelse(is.na(ligand_list[as.numeric(row[2])]) || row[2] == 0 , 0, ligand_list[as.numeric(row[2])])
        }
        
        
        
         locat_x <- df$meta$x[as.numeric(single_network[1])]
         locat_y <- df$meta$y[as.numeric(single_network[1])]
         
        
        new_expression_row <- c(receptor_expression, ligand_expression, locat_x, locat_y )
        
        
        dataset[[j]] <- rbind(dataset[[j]], new_expression_row)
        
        
      }
    }
        
    
    ds <- dataset
    means <- lapply(ds, colMeans)
   ds_matrix<- do.call(rbind, means)
   
   
   return(ds_matrix)
  }



ds_example <- build_dataset(df_star, star_example,"Sstr2" ,"Cort")




```

```{r}
ds_example <- build_dataset(df, lr_example)

ds_example


```


## SVC model 4
```{r}
 # model4 optimal method = BFGS, initial value = 0
SVC_model4 <- function(obj, lr,recepter,ligand , lambda1, lambda2) {
  
  ds_matrix <- build_dataset(obj, lr, recepter,ligand)[,c(1,2)]
  
  receiver <- obj$meta$cell_type[as.numeric(rownames(lr))[1]]
  sender <- obj$meta$cell_type[na.omit(as.numeric(lr))[1]]
  
  
  Y <- as.matrix(ds_matrix[,1],ncol = 1)
  X <- as.matrix(ds_matrix[,2],ncol = 1)
  X_0 <- as.matrix(rep(1, nrow(ds_matrix)),ncol = 1)
  X<- cbind(X_0, X, X)
  tau_2 = 1
 
  #function for beta0 and beta1
    objective_function <- function(beta) {
    
       obj1 <- matrix(beta, ncol = 1)
       int = obj1[1]
       beta_0 = obj1[2]
       beta_1 = as.vector(obj1[-c(1,2)])
    
       beta_new <- as.matrix(cbind(rep(int, length(beta_1)), rep(beta_0, length(beta_1)), beta_1))
       
       
   
       residuals = Y  - matrix(rowSums(X * beta_new), ncol = 1)
       
      tau = 1
 
      # Calculate the squared sum of residuals
      L <- 1/(2*tau*ncol(Y)) * sum(residuals^2) 

      # Calculate the penalty terms
      R1 <- lambda1 * sum(abs(beta))
      
      # Calculate the penalty term R2
      Dis <- as.matrix(obj$para$dist[obj$meta$cell_type == receiver, obj$meta$cell_type == receiver])
    
      
      sigma_2 = 1
      
      phi = 1
     
     weight <- exp(- phi * Dis)
     
      G <- sigma_2*weight
 
      
    beta_1 = as.matrix(beta_1)
   

      R2 = as.numeric(lambda2 *( t(beta_1) %*% G %*% beta_1))
 
      
      objective_value <- L + R1 + R2
      
      
# cat("L is", L, "\n")
#  cat("R1 is", R1, "\n")
#  cat("R2 is", R2, "\n")
#  cat("sum is", objective_value, "\n")
      return(objective_value)
    }
    

    result <- optim(par = matrix(rep(0, length(Y)+2),ncol = 1), fn = objective_function, method = "BFGS")
 
    beta_list <- result
    
    #likelihood test for /beta = 0
    
    
       int = beta_list$par[1]
       beta_0 = beta_list$par[2]
       beta_1 = as.vector(beta_list$par[-c(1,2)])
    
       beta_new <- as.matrix(cbind(intercept = rep(int, length(beta_1)), beta_0 = rep(beta_0, length(beta_1)), beta_1 = beta_1))
  

    likelihood_score <- 1/tau_2 * sum(Y - matrix(rowSums(X * beta_new), ncol = 1)^2)
    
    beta_list$score = likelihood_score
    beta_list$intercept = int
    beta_list$beta_0 = beta_0
    beta_list$beta_1 = beta_1
    
    return(beta_list) 
}
    

#beta_coefficients <- SVC_model4(df, lr_example, 
#                               lambda1 = 0.0001,
#                               lambda2 = 0.0001)


```





## permutation test
```{r}
per_test <- function(limit){
  time = 0
  chi2_list <- matrix()
  while (time < limit ){
    cat("time is", time,"\n")
    df <- Null_dataset_gen()
    
    lr <- get_lr_wknn(df,
            sender = 1,
            receiver = 2,
            k = 4)
    
    result <- SVC_model3(df,lr, lambda1 = 0, lambda2 = 0)
    
    
    chi2 = result$score
    
    chi2_list <- as.matrix(rbind(chi2_list, chi2))
    
    time = time + 1 
    
  }
  
  return(chi2_list)
}


list_new <- per_test(50)
list_50 <- rbind(list_50,list_new)

hist(list_50,breaks = 20,xlim=c(0,100))
```

## plot the result

```{r}
## plot the result

data_all<- vector("list",2)

#location
data_1 <- as.matrix(ds_example[,c(ncol(ds_example)-1, ncol(ds_example))],ncol = ncol(ds_example)-2)

# color
data_2 <- as.matrix(beta_coefficients$beta_1, ncol =1)
data_3 <- beta_coefficients$beta_0
data_deep <-  data_2 + data_3

#list of location
data_all[[1]] <- data.frame(x =data_1[,1], y = data_1[,2], color = data_deep )
data_all[[2]] <- data_3

data_lig <- data.frame(x = df$meta$x[df$meta$cell_type == 1], y = df$meta$y[df$meta$cell_type == 1])

data_els <- data.frame(
  x = df$meta$x[df$meta$cell_type == 3 | df$meta$cell_type == 4],
  y = df$meta$y[df$meta$cell_type == 3 | df$meta$cell_type == 4]
)


plot_result <- function(data_R,data_L,data_E){
  
ggplot() +
  geom_point(data = data_R[[1]], aes(x = x, y = y, color = color), size = 1.5) +
  scale_color_gradient2(low ="blue", mid = "yellow", high ="red", midpoint = 0,limits = c(-1,+1 )) +
  geom_point(data = data_L, aes(x = x, y = y), color = "darkgreen", size = 1) +
  geom_point(data = data_E, aes(x = x, y = y), color = "lightgray", size = 1) +

  theme_minimal()

}



plot_result(data_all, data_lig,data_els)


```
## function of ploting
```{r}
result_plot <- function (ds,df, coefficients,receiver,sender ){
  
  data_all<- vector("list",2)
  
  data_1 <- as.matrix(ds[,c(ncol(ds)-1, ncol(ds))],ncol = 2)

  data_2 <- as.matrix(coefficients$beta_1, ncol =1)
  data_3 <- coefficients$beta_0
  data_deep <-  data_2 + data_3
  
  data_all[[1]] <- data.frame(x =data_1[,1], y = data_1[,2], color = data_deep )
  data_all[[2]] <- data_3
 
  data_lig <- data.frame(x = df$meta$x[df$meta$cell_type == sender], y = df$meta$y[df$meta$cell_type == sender])
  

data_els <- data.frame(
  x = df$meta$x[df$meta$cell_type != sender & df$meta$cell_type != receiver],
  y = df$meta$y[df$meta$cell_type != sender & df$meta$cell_type != receiver]
)

plot_result(data_all, data_lig,data_els)
  
}

result_plot(ds_example,df_star,ds_coefficients, 'Astro', 'eL5')
```





## SVC model 5  not usefull
```{r}
 # model4 optimal method = , initial value = 0
SVC_model5 <- function(obj, lr, lambda1, lambda2) {
  
  ds_matrix <- build_dataset(obj, lr)[,c(1,2)]
  
  receiver <- obj$meta$cell_type[as.numeric(rownames(lr))[1]]
  sender <- obj$meta$cell_type[na.omit(as.numeric(lr))[1]]
  
  
  Y <- as.matrix(ds_matrix[,1],ncol = 1)
  X <- as.matrix(ds_matrix[,2],ncol = 1)
  X_0 <- as.matrix(rep(1, nrow(ds_matrix)),ncol = 1)
  X<- cbind(X_0, X, X)
 
    initial_params <- matrix(rep(0, length(Y) + 2), ncol = 1)
    result <- newton_raphson(objective_function, initial_params)
 
    beta_list <- result
    
    #likelihood test for /beta = 0
    
    
       int = beta_list$par[1]
       beta_0 = beta_list$par[2]
       beta_1 = as.vector(beta_list$par[-c(1,2)])
    
       beta_new <- as.matrix(cbind(intercept = rep(int, length(beta_1)), beta_0 = rep(beta_0, length(beta_1)), beta_1 = beta_1))
  

    likelihood_score <- 1/tau_2 * sum(Y - matrix(rowSums(X * beta_new), ncol = 1)^2)
    
    beta_list$score = likelihood_score
    beta_list$intercept = int
    beta_list$beta_0 = beta_0
    beta_list$beta_1 = beta_1
    
    return(beta_list) 
}
    
beta_coefficients <- SVC_model5(df, lr_example, 
                               lambda1 = 0.001,
                               lambda2 = 0.01)



```

