---
title: "cccmodel+opti"
author: "Wenjing Li"
date: "2023-08-30"
output: pdf_document
---
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(spdep)
library(RColorBrewer)
library(ggplot2)
library(optimx)
install.packages("spgwr")

```
# Finding Neighbour

## Weight KNN
```{r}
## Weighted K-NN for lr pairs

get_lr_wknn <- function(obj,sender,receiver, k){
  
  if(!all(c(sender, receiver) %in% unique(obj$meta$cell_type))) {
    stop("Can not find sender/receiver in the data")}
  
  else {
    
    #distance matrix
    
    distance <- obj$para$dist[obj$meta$cell_type == receiver, obj$meta$cell_type == sender]
    
    R <- list()
    
    #the indix of receiver
    R$indices <- as.matrix(t(head(apply(distance, 1, function(x) as.numeric(colnames(distance)[order(x,decreasing = FALSE)])),k)))
    
    
   #the distances of receiver from sender
    R$distances <- t(head(apply(distance, 1, function(x) sort(x, decreasing = FALSE)), k))
    
    weighted_counts <- R$distances
    percentile_weight <- head(sort(weighted_counts), length(weighted_counts) * 1)
    
    index_wknn <- t(apply(weighted_counts, 1 , function(x) x %in% percentile_weight))
    
     lr_wknn  <- R$indices * index_wknn
     
     lr_wknn[lr_wknn == 0 ] <- NA
     
     lr_wknn <- cbind(lr_wknn,obj$meta$locat[obj$meta$cell_type == receiver,])
     
     
     name <- c(c(1:k),"X","Y")
     
     
     colnames(lr_wknn) <-  name
    
    return(lr_wknn)
  }
}
  
  


```

## create lr index 
```{r}
 create_lr_index <- function(lrpair, Nopairadd = TRUE ){
   if(Nopairadd) {
    lrpair[,1]<- ifelse(is.na(lrpair[,1]), "0",lrpair[,1] )
   }
   
    A = rep(row.names(lrpair), each = ncol(lrpair)-2 )
    B = as.vector(t(lrpair[,-c(ncol(lrpair)-1, ncol(lrpair))]))
    
    lr_index <- cbind(A,B)
    
    lr_index <- lr_index[complete.cases(lr_index),]
    
    return(lr_index)
  }


```



##  plot lr pairs 


```{r}

find_row_list_number <- function(lr_index,list_of_lists) {
         
       for (i in 1: length(list_of_lists)) {
          if (all(lr_index %in% list_of_lists[[i]])) {
                       ind = i 
                        break
          }
       }
  return(ind)
}

plot_lr_pair <- function(obj, lr_pair, arrows = T, cluster = list()){
  #obj = df
  
    lr_index <- create_lr_index(lr_pair,Nopairadd = FALSE)
    
    lr_uni <- unique(as.vector(lr_index))
    
    lr_meta <- obj$meta$locat[lr_uni,]
    recepter <- obj$meta$cell_type[as.numeric(rownames(lr_pair)[1])]
    ligand <- obj$meta$cell_type[na.omit(as.numeric(as.matrix(lr_pair)))[1]]
     
     
    celltype <- as.vector(obj$meta$cell_type)
    ct_index <- as.vector(unique(celltype))
    color <- match(celltype,ct_index)
    
    
     plot(obj$meta$locat, pch = 19, cex = 0.5, col = ifelse(celltype %in% c(recepter, ligand), color, "grey"))

     text(x= obj$meta$locat$x, y = obj$meta$locat$y, obj$meta$cell, pos = 3)
  

for (i in 1:nrow(lr_index)) {
      #sender
       A = lr_index[i,2]
      #receiver
      B = lr_index[i,1]
      
      x1 <- lr_meta[rownames(lr_meta) == A, 1]
      y1 <- lr_meta[rownames(lr_meta) == A, 2]
      x2 <- lr_meta[rownames(lr_meta) == B, 1]
      y2 <- lr_meta[rownames(lr_meta) == B, 2]
      
      
if (length(cluster) == 0 ){
if (arrows)  {
   arrows(x1, y1, x2, y2, length = 0.1)
}
else{
    lines(c(x1, x2), c(y1, y2), col = 1 )
}
      
}
  else{
    
    if (arrows)  {
   arrows(x1, y1, x2, y2, length = 0.1, col =as.numeric(find_row_list_number(lr_index[i, ], cluster)))
     }
else{
      lines(c(x1, x2), c(y1, y2), col = as.numeric(find_row_list_number(lr_index[i, ],cluster)))
     }
  }
  
}
}




    
    
```


## find neighbourhoods
```{r}

find_network <- function(obj, lr_pairs, plot = TRUE) {
  
  find_neighbor <- function(lr_pairs, Nopairadd = TRUE){
    
  lr_index <- create_lr_index(lr_pairs)
  neighbor <- list()
  
  for (value in unique(lr_index[, 1])) {
    # Extract rows with the current value
    rows <- lr_index[lr_index[,1] == value, ]
    # Append the rows to the result list as a matrix
    neighbor[[length(neighbor) + 1]] <- matrix(rows, ncol = 2, byrow = FALSE)
  }
  
  # Return the result
  return(neighbor)
}
  
  if(plot){
    neighbor_plot <- find_neighbor(lr_pairs,Nopairadd = FALSE)
    plot_lr_pair(obj, lr_pairs, arrows = T, cluster = neighbor_plot)
    
  }
  
  

  network <- find_neighbor(lr_pairs)
  return(network)
  
}




```






# SVC model
##dataset generating

```{r}
 build_dataset <- function(df, lr,recepter,ligand ) {
    
    lr_network <- find_network(df, lr,plot = FALSE)
    
      
      recepter_list <- df$meta$gene[,colnames(df$meta$gene) == recepter]
      ligand_list <- df$meta$gene[,colnames(df$meta$gene) == ligand]
      
        dataset <- vector("list", length(lr_network))  
  
    for (j in 1:length(lr_network)) {
      single_network <- lr_network[[j]]
      
      for (i in 1:(length(single_network)/2)) {
        
        if (length(single_network) == 2) {
          receptor_expression <- ifelse(is.na(recepter_list[as.numeric(single_network[1])]), 0, recepter_list[as.numeric(single_network[1])])
          ligand_expression <- ifelse(is.na(ligand_list[as.numeric(single_network[2])]) || single_network[2] == 0 ,0,ligand_list[as.numeric(single_network[2])])
          
        } else {
          row <- single_network[i, ]
          receptor_expression <- ifelse(is.na(recepter_list[as.numeric(row[1])]), 0 , recepter_list[as.numeric(row[1])] )
          
          ligand_expression <- ifelse(is.na(ligand_list[as.numeric(row[2])]) || row[2] == 0 , 0, ligand_list[as.numeric(row[2])])
        }
        
        
        
         locat_x <- df$meta$locat$x[as.numeric(single_network[1])]
         locat_y <- df$meta$locat$y[as.numeric(single_network[1])]
         
        
        new_expression_row <- c(receptor_expression, ligand_expression, locat_x, locat_y )
        
        
        dataset[[j]] <- rbind(dataset[[j]], new_expression_row)
        
        
      }
    }
        
    
    ds <- dataset
    means <- lapply(ds, colMeans)
   ds_matrix<- do.call(rbind, means)
   
   
   return(ds_matrix)
  }





```





## SVC model4- process


## model with optimazation
```{r}
 # model4 optimal method = BFGS, initial value = 0
SVC_model4 <- function(obj,
                       lr,
                       recepter,
                       ligand,
                       lambda1, 
                       lambda2,
                       tau = 1,
                       phi = 1) {
  
  dataset <- build_dataset(obj, lr, recepter,ligand)

   Y = dataset[,1]
   X_1 = dataset[,2]
   X_0 <- as.matrix(rep(1, nrow(dataset)),ncol = 1)
   X<- cbind(X_0, X_1, X_1)
   Dis = as.matrix(dist(dataset[,c(3,4)]))
  
  receiver <- obj$meta$cell_type[as.numeric(rownames(lr))[1]]
  sender <- obj$meta$cell_type[na.omit(as.numeric(as.matrix(lr)))[1]]
  
  
   objective_function <- function(beta) {
   
   
       init_value <- matrix(beta, ncol = 1)
       intercept = init_value[1]
       beta_0 = init_value [2]
       beta_1 = as.vector(init_value[-c(1,2)])
       beta_new <- as.matrix(cbind(rep(intercept, length(beta_1)), rep(beta_0, length(beta_1)), beta_1))
   
       residuals = Y  - matrix(rowSums(X * beta_new), ncol = 1)
       
       #log likelihood
       L <- 1/tau^2 * sum(residuals^2) 
       
       # lasso penalty
       R1 <- lambda1 * sum(abs(beta_1))
       
       
       # Laplacian quadratic penalty
       weight <- exp(- phi * Dis)
       
       d <-  rowSums(weight)
       D <-  matrix(0, nrow = length(d), ncol = length(d))
       diag(D) <- d
       G <-  D - weight
       
       beta_1 = as.matrix(beta_1)
       
      R2 = lambda2 *( t(beta_1) %*% G %*% beta_1 )
 
      objective_value <- L + R1 + R2
      
      return(objective_value)
    }



    result <- optim(par = matrix(rep(0, nrow(dataset) + 2), ncol = 1), fn = objective_function, method = "BFGS")
 
    beta_list <- result
    
    #likelihood test for /beta = 0
    
    
       int = beta_list$par[1]
       beta_0 = beta_list$par[2]
       beta_1 = as.vector(beta_list$par[-c(1,2)])
       beta_new <- as.matrix(cbind(intercept = rep(int, length(beta_1)), beta_0 = rep(beta_0, length(beta_1)), beta_1 = beta_1))
  
    likelihood_score <- 1/tau^2 * sum((Y - matrix(rowSums(X * beta_new), ncol = 1))^2)
    
    beta_list$score = likelihood_score
    beta_list$intercept = int
    beta_list$beta_0 = beta_0
    beta_list$beta_1 = beta_1
    
    return(beta_list) 
}
    





```
  
  






## plot the result

## function of ploting
```{r}

plot_point <- function(data_all,data_L,data_E){
  
ggplot() +
  geom_point(data = data_all, aes(x = x, y = y, color = color), size = 1.5) +
  scale_color_gradient2(low ="green", mid = "yellow", high ="red", midpoint = 0,limits = c(-3,+3 )) +
  geom_point(data = data_L, aes(x = x, y = y), color = "darkgray", size = 1) +
  geom_point(data = data_E, aes(x = x, y = y), color = "lightgray", size = 1) +

  theme_minimal()

}


result_plot <- function (df, coefficients,receiver,sender, adjust = F ){
  
  data_1 <- data.frame(df$meta$locat$x[df$meta$cell_type == receiver], df$meta$locat$y[df$meta$cell_type == receiver])

  data_2 <- as.matrix(coefficients$beta_1, ncol =1)
  data_3 <- coefficients$beta_0
  if (!adjust){
  data_deep <-  data_2
  }
  else{
    data_deep <-  data_2 + data_3
  }
  
  data_all <- data.frame(x =data_1[,1], y = data_1[,2], color = data_deep )
 
  data_lig <- data.frame(x = df$meta$locat$x[df$meta$cell_type == sender], y =  df$meta$locat$y[df$meta$cell_type == sender])
  

data_els <- data.frame(
  x = df$meta$locat$x[df$meta$cell_type != sender & df$meta$cell_type != receiver],
  y = df$meta$locat$y[df$meta$cell_type != sender & df$meta$cell_type != receiver]
)

plot_point(data_all, data_lig,data_els)
  
}


```
