---
title: ''
output: pdf_document
date: "2023-08-08"
---

```{r setup}
install.packages(pkgs = 'devtools')
devtools::install_github('linxihui/NNLM')

devtools::install_github('ZJUFanLab/SpaTalk')

devtools::install_local("/path/to/SpaTalk-main.zip")

library("devtools")
library("NNLM")
library("SpaTalk")

# load demo data
load(paste0(system.file(package = 'SpaTalk'), "/extdata/starmap_data.rda"))
load(paste0(system.file(package = 'SpaTalk'), "/extdata/starmap_meta.rda"))


obj <- createSpaTalk(st_data = as.matrix(starmap_data),
                     st_meta = starmap_meta[, -4],
                     species = "Mouse",
                     if_st_is_sc = T,
                     spot_max_cell = 1)
# create SpaTalk data
obj <- dec_celltype(object = obj,
                    sc_data = as.matrix(starmap_data),
                    sc_celltype = starmap_meta$celltype)

# Filter LRIs with downstream targets
plot_st_celltype_percent(object = obj, celltype = 'eL5',size = 2)

plot_st_celltype_percent(object = obj, celltype = 'Astro',size = 2)


plot_st_cor_heatmap(object = obj,
                    marker_genes = c("Plp1","Vip","Sst","Lamp5","Pcp4","Sstr2","Cort"),
                    celltypes = c("Oligo","VIP","SST","eL2_3","eL6","Astro","eL5"),
                    scale = "none",
                    color_low = 'blue',
                    color_high = 'yellow',
                    color_mid = 'yellow')

obj@meta$rawmeta$celltype <- starmap_meta$celltype
obj <- find_lr_path(object = obj, lrpairs = lrpairs, pathways = pathways)
obj <- c(object = obj, 
               celltype_sender = 'eL5',
               celltype_receiver = 'Astro')

```

```{r}


```


```{r}
plot_ccdist(object = obj,
            celltype_sender = 'eL5',
            celltype_receiver = 'Astro',            
            size = 2,
            arrow_length = 0.1)

```

```{r}
obj_lr_path1 <- get_lr_path(object = obj,
                           celltype_sender = 'eL5',
                           celltype_receiver = 'Astro',
                           ligand = 'Cort',
                           receptor = 'Sstr2')
obj_lr_path1
plot_lrpair(object = obj,
            celltype_sender = 'eL5',
            ligand = 'Cort',
            celltype_receiver = 'Astro',
            receptor = 'Sstr2',
            if_plot_density = F,
            size = 2,
            arrow_length = 0.1)
result_plot(ds_example2,df_star,ds_coefficients2, 'Astro', 'eL5')

```

```{r}

obj_lr_path2 <- get_lr_path(object = obj,
                           celltype_sender = 'eL5',
                           celltype_receiver = 'Astro',
                           ligand = 'S100a10',
                           receptor = 'Trpv6')
obj_lr_path2


plot_lrpair(object = obj,
            celltype_sender = 'eL5',
            ligand = 'S100a10',
            celltype_receiver = 'Astro',
            receptor = 'Trpv6',
            if_plot_density = F,
            size = 2,
            arrow_length = 0.1)
result_plot(ds_example,df_star,ds_coefficients1, 'Astro', 'eL5')
```


