---
title: "Simulation"
author: "Wenjing Li"
date: "2023-08-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("dplyr")
library("dplyr")
```

#Null similation
```{r}

Null_dataset_gen<-function(){
df <- list()
df$meta <- list()
df$meta$cell <- c(1:500)
df$meta$x <- runif(500, min = 0, max = 100)
df$meta$y <- runif(500, min = 0, max = 100)
gene1 <- c(rep(0, 200), rep(1, 100), rep(0, 100), rep(1, 100))
gene2 <- c(rep(0, 200), rep(0, 100), rep(1, 100), rep(1, 100))
df$meta$gene <- cbind(gene1,gene2)
colnames(df$meta$gene) = c(1:2)
df$meta$locat <- data.frame(df$meta$x,df$meta$y)
df$para$dist <- as.matrix(dist(df$meta$locat))
df$meta$cell_type<- sample(1:4, length(df$meta$cell), replace = TRUE)
return(df)
}
df = Null_dataset_gen()
```


#Simulation with known variable
```{r}
set.seed(1)

Sim_dataset_gen <- function() {

df<- list()


# index for ys
df$meta$cell <- c(1:100)
x <- seq(5, 100, by = 10)
y <- seq(5, 100, by = 10)
df$meta$locat <- expand.grid(x,y)
colnames(df$meta$locat) <- c("x","y")

gene1 <- runif(100, min = 0, max = 3)
df$meta$gene <- cbind(gene1 , 0)
colnames(df$meta$gene) <- c("gene1","gene2")
df$meta$cell_type <- c(rep(1,100),rep(2,300))

df_data_frame <- as.data.frame(cbind(df$meta$cell,df$meta$locat))

cell_1<- df_data_frame %>%
  filter(x > 50 & y > 50) %>%
  select(1) %>%
  unlist()
cell_2<- df_data_frame %>%
  filter(x <= 50 & y > 50) %>%
  select(1) %>%
  unlist()

cell_3<- df_data_frame %>%
  filter(x <= 50 & y <= 50) %>%
  select(1) %>%
  unlist()

cell_4<- df_data_frame %>%
  filter(x > 50 & y <= 50) %>%
  select(1) %>%
  unlist()

cell_list <- cbind(cell_1, cell_2,cell_3,cell_4)


#index for xs
#x_1
df$meta$cell <- c(df$meta$cell,c(101:200))
x <- seq(5+1, 100+1, by = 10)
y <- seq(5, 100, by = 10)
location <- expand.grid(x,y)
colnames(location) <- c("x","y")
df$meta$locat <- rbind(df$meta$locat,location)
cell_list2 <- cell_list + 100
df$meta$gene <- rbind(df$meta$gene, matrix(rep(0,200), ncol =2))

# first Quadrant( beta_1 = 1)
gene1_1<- df$meta$gene[cell_list[,1],1]
df$meta$gene[cell_list2[,1],2] =  (gene1_1 -1 )/2
#+ rnorm(n = 100, mean = 0, sd = 0.1)

# Second Quadrant( beta_1 = 0)
gene1_2<- df$meta$gene[cell_list[,2],1]
df$meta$gene[cell_list2[,2],2] =  gene1_2 -1
#+ rnorm(n = 100, mean = 0, sd = 0.1)
  
# Third Quadrant( beta_1 = -1)
gene1_3<- df$meta$gene[cell_list[,3],1]
df$meta$gene[cell_list[,3],1] <- 1
df$meta$gene[cell_list2[,3],2] = gene1_3



#+ rnorm(n = 100, mean = 0, sd = 0.1)

# Fourth Quadrant( beta_1 = 0)
gene1_4<- df$meta$gene[cell_list[,4],1]
df$meta$gene[cell_list2[,4],2] =  gene1_4 -1






#x_2

df$meta$cell <- c(df$meta$cell,c(201:300))
x <- seq(5, 100, by = 10)
y <- seq(5+1, 100+1, by = 10)
location <- expand.grid(x,y)
colnames(location) <- c("x","y")
df$meta$locat <- rbind(df$meta$locat,location)
cell_list3 <- cell_list + 200
df$meta$gene <- rbind(df$meta$gene, matrix(rep(0,200), ncol =2))

# first Quadrant
df$meta$gene[cell_list3[,1],2] = (gene1_1 -1 )/2
#+ rnorm(n = 100, mean = 0, sd = 0.1)

# Second Quadrant
df$meta$gene[cell_list3[,2],2] = gene1_2 -1
#+ rnorm(n = 100, mean = 0, sd = 0.1)
  
# Third Quadrant
df$meta$gene[cell_list3[,3],2] = gene1_3
#+ rnorm(n = 100, mean = 0, sd = 0.1)

# Fourth Quadrant
df$meta$gene[cell_list3[,4],2] =  gene1_4 -1 





#x_3
df$meta$cell <- c(df$meta$cell,c(301:400))
x <- seq(5, 100, by = 10)
y <- seq(5-1, 100-1, by = 10)
location <- expand.grid(x,y)
colnames(location) <- c("x","y")
df$meta$locat <- rbind(df$meta$locat,location)
cell_list4 <- cell_list + 300
df$meta$gene <- rbind(df$meta$gene, matrix(rep(0,200), ncol =2))

# first Quadrant
df$meta$gene[cell_list4[,1],2] = (gene1_1 -1 )/2
#+ rnorm(n = 100, mean = 0, sd = 0.1)

# Second Quadrant
df$meta$gene[cell_list4[,2],2] = gene1_2 -1
#+ rnorm(n = 100, mean = 0, sd = 0.1)
  
# Third Quadrant
df$meta$gene[cell_list4[,3],2] = gene1_3
#+ rnorm(n = 100, mean = 0, sd = 0.1)

# Fourth Quadrant
df$meta$gene[cell_list4[,4],2] = gene1_4 -1 



df$para$dist <- as.matrix(dist(df$meta$locat))

     
     return(df)
}

df2 <- Sim_dataset_gen()
plot(df2$meta$locat, pch = 19, cex = 0.5, col = ifelse(df2$meta$cell_type %in% "1" , "black", "grey"))

     text(x= df2$meta$locat$x, y = df2$meta$locat$y, df2$meta$cell, pos = 3)

     



```



# Finding Neighbour

```{r}
## Weight KNN
lr_example2 <- get_lr_wknn(df2,
        sender = 2 ,
           receiver = 1,
          k = 3)

## create lr index 
lr_index_example2 <- create_lr_index(lr_example2)



##  plot lr pairs 
lr_pair2 <- plot_lr_pair(df2, lr_example2)

## find neighbourhoods
find_network(df2,lr_example2)
```





# SVC model

```{r}
## dataset generating

dataset2 <- build_dataset(df2, lr_example2,"gene1","gene2")

## SVC model
debug(SVC_model4)


initial_params <- matrix(rep(0, nrow(dataset2) + 2), ncol = 1)


 

model1 <- SVC_model4(df2, lr_example2, 
                          recepter = "gene1",
                           ligand = "gene2",
                          lambda1 = 0,
                           lambda2 = 0)


## result ploting

result_plot(df2, model1, 1, 2, adjust = F)


```
## result of simulated dataset
```{r}
## plot the result


#location
data_1 <- data.frame(df2$meta$locat$x[df2$meta$cell_type == 1], df2$meta$locat$y[df2$meta$cell_type == 1])

# color
data_2<- rep(0, sum(df2$meta$cell_type == 1))
data_2[df2$meta$locat$x > 50 & df2$meta$locat$y > 50 & df2$meta$cell_type == 1] <- 1
data_2[df2$meta$locat$x <= 50 & df2$meta$locat$y <= 50 & df2$meta$cell_type == 1] <- -1
  data_2<-data_2[c(1:100)]

data_3 <- 1
data_deep <-  data_2 

#list of location
data_all <- data.frame(x =data_1[,1], y = data_1[,2], color = data_deep )

data_lig <- data.frame(x = df2$meta$locat$x[df2$meta$cell_type == 2], y = df2$meta$locat$y[df2$meta$cell_type == 2])

data_els <- data.frame(
  x = df2$meta$locat$x[df2$meta$cell_type !=1 & df2$meta$cell_type != 2],
  y =df2$meta$locat$y[df2$meta$cell_type !=1 & df2$meta$cell_type !=2 ]
)





plot_point(data_all, data_lig,data_els)


```





## permutation test
```{r}
per_test <- function(limit){
  time = 0
  chi2_list <- matrix()
  while (time < limit ){
    cat("time is", time,"\n")
    df <- Null_dataset_gen()
    
    lr <- get_lr_wknn(df,
            sender = 1,
            receiver = 2,
            k = 4)
    
    result <- SVC_model3(df,lr, lambda1 = 0, lambda2 = 0)
    
    
    chi2 = result$score
    
    chi2_list <- as.matrix(rbind(chi2_list, chi2))
    
    time = time + 1 
    
  }
  
  return(chi2_list)
}


list_new <- per_test(50)
list_50 <- rbind(list_50,list_new)

hist(list_50,breaks = 20,xlim=c(0,100))
```



